import type { MenuItem, OrderStatusStep, Restaurant } from './types';

const pizzaModifiers = [
  {
    id: "size",
    name: "Size",
    type: 'single' as const,
    required: true,
    options: [
      { id: "small", name: "Small", priceDeltaCents: 0 },
      { id: "medium", name: "Medium", priceDeltaCents: 300 },
      { id: "large", name: "Large", priceDeltaCents: 600 },
      { id: "xl", name: "XL", priceDeltaCents: 900 },
    ],
  },
  {
    id: "crust",
    name: "Crust",
    type: 'single' as const,
    required: true,
    options: [
      { id: "classic", name: "Classic hand-tossed", priceDeltaCents: 0 },
      { id: "thin", name: "Crispy thin", priceDeltaCents: 150 },
      { id: "sourdough", name: "Sourdough", priceDeltaCents: 225 },
      { id: "gluten-free", name: "Gluten-free", priceDeltaCents: 300 },
      { id: "stuffed", name: "Cheese-stuffed", priceDeltaCents: 350 },
    ],
  },
  {
    id: "cheese",
    name: "Cheese",
    type: 'multiple' as const,
    maxSelected: 3,
    options: [
      { id: "mozzarella", name: "Mozzarella", priceDeltaCents: 0 },
      { id: "extra-cheese", name: "Extra cheese", priceDeltaCents: 175 },
      { id: "fresh-mozzarella", name: "Fresh mozzarella", priceDeltaCents: 225 },
      { id: "smoked-provolone", name: "Smoked provolone", priceDeltaCents: 225 },
      { id: "ricotta", name: "Whipped ricotta", priceDeltaCents: 200 },
      { id: "parmesan", name: "Aged parmesan", priceDeltaCents: 150 },
      { id: "goat-cheese", name: "Goat cheese", priceDeltaCents: 250 },
      { id: "vegan-cheese", name: "Vegan cheese", priceDeltaCents: 275 },
      { id: "burrata", name: "Burrata", priceDeltaCents: 350 },
    ],
  },
  {
    id: "toppings",
    name: "Toppings",
    type: 'multiple' as const,
    maxSelected: 6,
    options: [
      { id: "pepperoni", name: "Pepperoni", priceDeltaCents: 150 },
      { id: "cup-and-char-pepperoni", name: "Cup-and-char pepperoni", priceDeltaCents: 225 },
      { id: "italian-sausage", name: "Italian sausage", priceDeltaCents: 200 },
      { id: "grilled-chicken", name: "Grilled chicken", priceDeltaCents: 250 },
      { id: "bacon", name: "Applewood bacon", priceDeltaCents: 225 },
      { id: "mushrooms", name: "Roasted mushrooms", priceDeltaCents: 125 },
      { id: "jalapenos", name: "Jalapeños", priceDeltaCents: 100 },
      { id: "caramelized-onions", name: "Caramelized onions", priceDeltaCents: 125 },
      { id: "black-olives", name: "Black olives", priceDeltaCents: 100 },
      { id: "banana-peppers", name: "Banana peppers", priceDeltaCents: 125 },
      { id: "pineapple", name: "Pineapple", priceDeltaCents: 125 },
      { id: "basil", name: "Fresh basil", priceDeltaCents: 75 },
      { id: "arugula", name: "Arugula", priceDeltaCents: 125 },
      { id: "truffle-oil", name: "Truffle oil", priceDeltaCents: 300 },
      { id: "hot-honey", name: "Hot honey drizzle", priceDeltaCents: 150 },
      { id: "garlic-confit", name: "Garlic confit", priceDeltaCents: 175 },
    ],
  },
];

function pizzaItem(item: Omit<MenuItem, 'modifierGroups'>): MenuItem {
  return { ...item, modifierGroups: pizzaModifiers };
}

export const restaurants: Restaurant[] = [
  {
    id: "marios-pizza",
    name: "Mario's Pizza Lab",
    cuisine: "Pizza",
    rating: 4.8,
    deliveryMinutes: "20–30 min",
    deliveryFeeCents: 199,
    imageEmoji: "🍕",
    tags: ["Popular", "Thin crust", "Open late"],
    menu: [
      pizzaItem({
        id: "margherita",
        name: "Classic Margherita",
        description: "Tomato, mozzarella, basil, olive oil.",
        priceCents: 1299,
        imageEmoji: "🌿",
        popular: true,
      }),
      pizzaItem({
        id: "pepperoni-feast",
        name: "Pepperoni Feast",
        description: "Double pepperoni, mozzarella, red sauce.",
        priceCents: 1499,
        imageEmoji: "🍕",
        popular: true,
      }),
      pizzaItem({
        id: "garden-supreme",
        name: "Garden Supreme",
        description: "Bell peppers, mushrooms, onions, olives.",
        priceCents: 1399,
        imageEmoji: "🫑",
      }),
      pizzaItem({
        id: "truffle-burrata",
        name: "Truffle Burrata Cloud",
        description: "Burrata, truffle oil, roasted mushrooms, basil.",
        priceCents: 1899,
        imageEmoji: "☁️",
      }),
    ],
  },
  {
    id: "slice-station",
    name: "Slice Station",
    cuisine: "Pizza",
    rating: 4.6,
    deliveryMinutes: "15–25 min",
    deliveryFeeCents: 249,
    imageEmoji: "🚉",
    tags: ["Fast", "NY style"],
    menu: [
      pizzaItem({
        id: "ny-cheese",
        name: "NY Cheese Slice Box",
        description: "Foldable cheese pizza with oregano dust.",
        priceCents: 1199,
        imageEmoji: "🧀",
        popular: true,
      }),
      pizzaItem({
        id: "spicy-vodka",
        name: "Spicy Vodka Pizza",
        description: "Vodka sauce, chili flakes, parmesan.",
        priceCents: 1599,
        imageEmoji: "🌶️",
        popular: true,
      }),
      pizzaItem({
        id: "soho-white",
        name: "SoHo White Pie",
        description: "Ricotta, mozzarella, garlic confit, cracked pepper.",
        priceCents: 1699,
        imageEmoji: "🤍",
      }),
      pizzaItem({
        id: "subway-supreme",
        name: "Subway Supreme",
        description: "Sausage, peppers, olives, onions, mozzarella.",
        priceCents: 1599,
        imageEmoji: "🚇",
      }),
    ],
  },
  {
    id: "dough-and-co",
    name: "Dough & Co.",
    cuisine: "Pizza",
    rating: 4.7,
    deliveryMinutes: "25–35 min",
    deliveryFeeCents: 99,
    imageEmoji: "🔥",
    tags: ["Wood fired", "Best value"],
    menu: [
      pizzaItem({
        id: "wood-fired-trio",
        name: "Wood-Fired Trio",
        description: "Three-cheese blend, charred crust, basil.",
        priceCents: 1699,
        imageEmoji: "🔥",
        popular: true,
      }),
      pizzaItem({
        id: "bbq-chicken",
        name: "BBQ Chicken Pizza",
        description: "Chicken, BBQ sauce, red onion, cilantro.",
        priceCents: 1599,
        imageEmoji: "🍗",
      }),
      pizzaItem({
        id: "ember-mushroom",
        name: "Ember Mushroom",
        description: "Roasted mushrooms, smoked provolone, thyme.",
        priceCents: 1799,
        imageEmoji: "🍄",
      }),
      pizzaItem({
        id: "hot-honey-soppressata",
        name: "Hot Honey Soppressata",
        description: "Soppressata-style pepperoni, hot honey, mozzarella.",
        priceCents: 1899,
        imageEmoji: "🍯",
        popular: true,
      }),
    ],
  },
  {
    id: "neapolitan-nova",
    name: "Neapolitan Nova",
    cuisine: "Pizza",
    rating: 4.9,
    deliveryMinutes: "30–40 min",
    deliveryFeeCents: 299,
    imageEmoji: "🇮🇹",
    tags: ["Neapolitan", "Wood fired", "Premium"],
    menu: [
      pizzaItem({
        id: "san-marzano-star",
        name: "San Marzano Star",
        description: "San Marzano tomato, fresh mozzarella, basil.",
        priceCents: 1799,
        imageEmoji: "⭐",
        popular: true,
      }),
      pizzaItem({
        id: "diavola-nova",
        name: "Diavola Nova",
        description: "Spicy salami-style pepperoni, chili oil, mozzarella.",
        priceCents: 1899,
        imageEmoji: "🌋",
      }),
      pizzaItem({
        id: "prosciutto-arugula",
        name: "Prosciutto & Arugula",
        description: "Cured-style prosciutto, arugula, parmesan, lemon oil.",
        priceCents: 1999,
        imageEmoji: "🥬",
      }),
      pizzaItem({
        id: "pesto-verde",
        name: "Pesto Verde",
        description: "Basil pesto, ricotta, roasted tomatoes, pine nuts.",
        priceCents: 1849,
        imageEmoji: "💚",
      }),
    ],
  },
  {
    id: "detroit-depth",
    name: "Detroit Depth",
    cuisine: "Pizza",
    rating: 4.7,
    deliveryMinutes: "25–35 min",
    deliveryFeeCents: 199,
    imageEmoji: "🧱",
    tags: ["Detroit style", "Crispy edges"],
    menu: [
      pizzaItem({
        id: "motor-city-red-top",
        name: "Motor City Red Top",
        description: "Brick cheese-style blend, sauce stripes, crispy corners.",
        priceCents: 1799,
        imageEmoji: "🟥",
        popular: true,
      }),
      pizzaItem({
        id: "pepperoni-corners",
        name: "Pepperoni Corners",
        description: "Cup-and-char pepperoni, caramelized cheese edge.",
        priceCents: 1899,
        imageEmoji: "🔶",
        popular: true,
      }),
      pizzaItem({
        id: "blue-line-bbq",
        name: "Blue Line BBQ Chicken",
        description: "BBQ chicken, smoked provolone, red onion.",
        priceCents: 1849,
        imageEmoji: "🏒",
      }),
      pizzaItem({
        id: "garlic-ranch-depth",
        name: "Garlic Ranch Depth",
        description: "Garlic sauce, mozzarella, bacon, ranch drizzle.",
        priceCents: 1749,
        imageEmoji: "🧄",
      }),
    ],
  },
  {
    id: "vegan-vinyl",
    name: "Vegan Vinyl Pizza",
    cuisine: "Vegan Pizza",
    rating: 4.5,
    deliveryMinutes: "20–30 min",
    deliveryFeeCents: 149,
    imageEmoji: "🎵",
    tags: ["Vegan", "Plant-based"],
    menu: [
      pizzaItem({
        id: "plant-pepperoni",
        name: "Plant Pepperoni Spin",
        description: "Plant pepperoni, vegan cheese, tomato sauce.",
        priceCents: 1699,
        imageEmoji: "🌱",
        popular: true,
      }),
      pizzaItem({
        id: "cashew-cream-fungi",
        name: "Cashew Cream Fungi",
        description: "Cashew cream, mushrooms, garlic confit, arugula.",
        priceCents: 1799,
        imageEmoji: "🍄",
      }),
      pizzaItem({
        id: "garden-groove",
        name: "Garden Groove",
        description: "Peppers, olives, onions, basil, vegan mozzarella.",
        priceCents: 1599,
        imageEmoji: "🎶",
      }),
      pizzaItem({
        id: "bbq-jackfruit",
        name: "BBQ Jackfruit Jam",
        description: "BBQ jackfruit, red onion, vegan cheese.",
        priceCents: 1749,
        imageEmoji: "🎸",
      }),
    ],
  },
  {
    id: "chicago-square",
    name: "Chicago Square Cut",
    cuisine: "Pizza",
    rating: 4.6,
    deliveryMinutes: "35–45 min",
    deliveryFeeCents: 299,
    imageEmoji: "🏙️",
    tags: ["Tavern style", "Square cut"],
    menu: [
      pizzaItem({
        id: "tavern-classic",
        name: "Tavern Classic",
        description: "Thin crust, sausage, green pepper, square cut.",
        priceCents: 1599,
        imageEmoji: "⬜",
        popular: true,
      }),
      pizzaItem({
        id: "deep-dish-lite",
        name: "Deep Dish Lite",
        description: "Pan crust, chunky tomato, mozzarella, parmesan.",
        priceCents: 1899,
        imageEmoji: "🥘",
      }),
      pizzaItem({
        id: "giardiniera-heat",
        name: "Giardiniera Heat",
        description: "Hot giardiniera, sausage, mozzarella.",
        priceCents: 1799,
        imageEmoji: "🌶️",
      }),
      pizzaItem({
        id: "lakefront-veggie",
        name: "Lakefront Veggie",
        description: "Spinach, mushrooms, onions, olives, ricotta.",
        priceCents: 1699,
        imageEmoji: "🌊",
      }),
    ],
  },
  {
    id: "california-crust",
    name: "California Crust Co.",
    cuisine: "Pizza",
    rating: 4.7,
    deliveryMinutes: "20–30 min",
    deliveryFeeCents: 199,
    imageEmoji: "🌴",
    tags: ["Fresh", "California"],
    menu: [
      pizzaItem({
        id: "avocado-ranch",
        name: "Avocado Ranch Chicken",
        description: "Chicken, avocado crema, ranch, tomatoes.",
        priceCents: 1899,
        imageEmoji: "🥑",
        popular: true,
      }),
      pizzaItem({
        id: "farmers-market",
        name: "Farmers Market Pie",
        description: "Seasonal vegetables, goat cheese, basil.",
        priceCents: 1799,
        imageEmoji: "🥕",
      }),
      pizzaItem({
        id: "surfside-pesto",
        name: "Surfside Pesto",
        description: "Pesto, mozzarella, artichokes, roasted tomatoes.",
        priceCents: 1849,
        imageEmoji: "🏄",
      }),
      pizzaItem({
        id: "golden-state-bbq",
        name: "Golden State BBQ",
        description: "BBQ sauce, chicken, pineapple, jalapeños.",
        priceCents: 1799,
        imageEmoji: "☀️",
      }),
    ],
  },
  {
    id: "midnight-marinara",
    name: "Midnight Marinara",
    cuisine: "Pizza",
    rating: 4.4,
    deliveryMinutes: "25–40 min",
    deliveryFeeCents: 349,
    imageEmoji: "🌙",
    tags: ["Late night", "Spicy"],
    menu: [
      pizzaItem({
        id: "after-hours-pepperoni",
        name: "After Hours Pepperoni",
        description: "Pepperoni, hot honey, chili flakes.",
        priceCents: 1699,
        imageEmoji: "🕛",
        popular: true,
      }),
      pizzaItem({
        id: "black-olive-moon",
        name: "Black Olive Moon",
        description: "Black olives, mushrooms, mozzarella, oregano.",
        priceCents: 1549,
        imageEmoji: "🌑",
      }),
      pizzaItem({
        id: "midnight-meatball",
        name: "Midnight Meatball",
        description: "Meatballs, marinara, ricotta, parmesan.",
        priceCents: 1899,
        imageEmoji: "🍝",
      }),
      pizzaItem({
        id: "garlic-knight",
        name: "Garlic Knight White Pie",
        description: "Garlic confit, ricotta, mozzarella, parmesan.",
        priceCents: 1749,
        imageEmoji: "🛡️",
      }),
    ],
  },
  {
    id: "brooklyn-basil",
    name: "Brooklyn Basil Works",
    cuisine: "Pizza",
    rating: 4.8,
    deliveryMinutes: "20–35 min",
    deliveryFeeCents: 249,
    imageEmoji: "🌉",
    tags: ["Artisan", "Brooklyn style"],
    menu: [
      pizzaItem({
        id: "basil-works-classic",
        name: "Basil Works Classic",
        description: "Fresh mozzarella, basil, tomato, parmesan.",
        priceCents: 1599,
        imageEmoji: "🌿",
        popular: true,
      }),
      pizzaItem({
        id: "brooklyn-bee-sting",
        name: "Brooklyn Bee Sting",
        description: "Pepperoni, hot honey, mozzarella, chili.",
        priceCents: 1899,
        imageEmoji: "🐝",
        popular: true,
      }),
      pizzaItem({
        id: "ricotta-rooftop",
        name: "Ricotta Rooftop",
        description: "Whipped ricotta, lemon zest, garlic, basil.",
        priceCents: 1799,
        imageEmoji: "🏢",
      }),
      pizzaItem({
        id: "sausage-and-fennel",
        name: "Sausage & Fennel",
        description: "Italian sausage, fennel, onions, smoked provolone.",
        priceCents: 1849,
        imageEmoji: "🌭",
      }),
    ],
  },
  {
    id: "mountain-pie",
    name: "Mountain Pie Lodge",
    cuisine: "Pizza",
    rating: 4.6,
    deliveryMinutes: "30–45 min",
    deliveryFeeCents: 199,
    imageEmoji: "🏔️",
    tags: ["Hearty", "Lodge style"],
    menu: [
      pizzaItem({
        id: "alpine-four-cheese",
        name: "Alpine Four Cheese",
        description: "Mozzarella, provolone, parmesan, goat cheese.",
        priceCents: 1849,
        imageEmoji: "🧀",
        popular: true,
      }),
      pizzaItem({
        id: "campfire-bacon",
        name: "Campfire Bacon",
        description: "Bacon, mushrooms, smoked provolone, BBQ drizzle.",
        priceCents: 1899,
        imageEmoji: "🏕️",
      }),
      pizzaItem({
        id: "forager-pie",
        name: "Forager Pie",
        description: "Mushrooms, garlic confit, truffle oil, arugula.",
        priceCents: 1999,
        imageEmoji: "🍄",
      }),
      pizzaItem({
        id: "pineapple-peak",
        name: "Pineapple Peak",
        description: "Pineapple, bacon, jalapeños, mozzarella.",
        priceCents: 1749,
        imageEmoji: "🍍",
      }),
    ],
  },
  {
    id: "spice-route-pizza",
    name: "Spice Route Pizza",
    cuisine: "Pizza",
    rating: 4.7,
    deliveryMinutes: "25–35 min",
    deliveryFeeCents: 199,
    imageEmoji: "🛺",
    tags: ["Bold flavors", "Fusion"],
    menu: [
      pizzaItem({
        id: "tikka-masala-pie",
        name: "Tikka Masala Pie",
        description: "Tikka-style sauce, chicken, onions, mozzarella.",
        priceCents: 1899,
        imageEmoji: "🍛",
        popular: true,
      }),
      pizzaItem({
        id: "paneer-pepper",
        name: "Paneer Pepper Pizza",
        description: "Paneer, bell peppers, onions, cilantro chutney drizzle.",
        priceCents: 1799,
        imageEmoji: "🧈",
      }),
      pizzaItem({
        id: "chili-corn-chaat",
        name: "Chili Corn Chaat",
        description: "Corn, jalapeños, onions, chaat spice, cheese.",
        priceCents: 1699,
        imageEmoji: "🌽",
      }),
      pizzaItem({
        id: "bombay-bbq",
        name: "Bombay BBQ Chicken",
        description: "BBQ chicken, masala onions, smoked provolone.",
        priceCents: 1849,
        imageEmoji: "🔥",
      }),
    ],
  },
];

export const orderStatusSteps: OrderStatusStep[] = [
  {
    status: "Placed",
    label: "Order placed",
    description: "Mock order received. No payment charged.",
    etaMinutesFromOrder: 0,
  },
  {
    status: "Confirmed",
    label: "Restaurant confirmed",
    description: "The restaurant accepted the order.",
    etaMinutesFromOrder: 2,
  },
  {
    status: "Preparing",
    label: "Preparing",
    description: "Kitchen is preparing the pizza.",
    etaMinutesFromOrder: 8,
  },
  {
    status: "Out for delivery",
    label: "Out for delivery",
    description: "Driver is on the way.",
    etaMinutesFromOrder: 22,
  },
  {
    status: "Delivered",
    label: "Delivered",
    description: "Mock delivery complete.",
    etaMinutesFromOrder: 35,
  },
];

export function validateFixtures(): string[] {
  const errors: string[] = [];
  for (const restaurant of restaurants) {
    if (restaurant.menu.length === 0) errors.push(`${restaurant.name} has no menu items.`);
    for (const item of restaurant.menu) {
      if (item.modifierGroups.length === 0) errors.push(`${item.name} has no modifiers.`);
      for (const group of item.modifierGroups) {
        if (group.required && group.options.length === 0) errors.push(`${item.name}/${group.name} is required but empty.`);
      }
    }
  }
  return errors;
}
